<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>IT Helpdesk Report</title>
    <style>
        body { font-family: sans-serif; color: #2d2d2d; font-size: 12px; line-height: 1.5; margin: 0; padding: 20px; }
        h1 { font-size: 20px; border-bottom: 1px solid #2d2d2d; padding-bottom: 10px; margin-bottom: 20px; text-transform: uppercase; letter-spacing: 1px; }
        h2 { font-size: 14px; margin-top: 30px; margin-bottom: 10px; text-transform: uppercase; color: #555; }
        .grid { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .grid td { padding: 10px; border: 1px solid #e5e5e5; text-align: center; }
        .grid td.label { font-size: 10px; text-transform: uppercase; color: #555; letter-spacing: 1px; }
        .grid td.value { font-size: 24px; font-weight: bold; }
        .grid td.dark { background: #2d2d2d; color: #fff; }
        .grid td.dark .label { color: #aaa; }
        table.list { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        table.list th { background: #f7f7f7; color: #555; font-size: 10px; text-transform: uppercase; padding: 8px; text-align: left; border-bottom: 1px solid #e5e5e5; }
        table.list td { padding: 8px; border-bottom: 1px solid #f0f0f0; }
        .footer { position: fixed; bottom: -20px; left: 0; right: 0; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #e5e5e5; padding-top: 10px; }
    </style>
</head>
<body>

    <h1>{{ $title }}</h1>

    <table class="grid">
        <tr>
            <td>
                <div class="label">Total Tickets</div>
                <div class="value">{{ $stats['total'] }}</div>
            </td>
            <td class="dark">
                <div class="label">Pending</div>
                <div class="value">{{ $stats['pending'] }}</div>
            </td>
            <td>
                <div class="label">In Progress</div>
                <div class="value">{{ $stats['in_progress'] + $stats['approved'] }}</div>
            </td>
            <td>
                <div class="label">Resolved</div>
                <div class="value">{{ $stats['resolved'] }}</div>
            </td>
        </tr>
    </table>

    <table style="width: 100%;">
        <tr>
            <td style="width: 50%; vertical-align: top; padding-right: 10px;">
                <h2>By Service Type</h2>
                <table class="list">
                    @forelse($stats['by_service'] as $row)
                    <tr>
                        <td>{{ $row['label'] }}</td>
                        <td style="text-align: right; font-weight: bold;">{{ $row['count'] }}</td>
                    </tr>
                    @empty
                    <tr><td colspan="2" style="color: #999; font-style: italic;">No data available.</td></tr>
                    @endforelse
                </table>
            </td>
            <td style="width: 50%; vertical-align: top; padding-left: 10px;">
                <h2>Other Statuses</h2>
                <table class="list">
                    <tr>
                        <td>Disapproved</td>
                        <td style="text-align: right; font-weight: bold;">{{ $stats['disapproved'] }}</td>
                    </tr>
                    <tr>
                        <td>Cancelled</td>
                        <td style="text-align: right; font-weight: bold;">{{ $stats['cancelled'] }}</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

    <h2>Recent Tickets (Selected Period)</h2>
    <table class="list">
        <thead>
            <tr>
                <th>Ticket No</th>
                <th>Date</th>
                <th>Service Type</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($tickets->take(20) as $ticket)
            <tr>
                <td style="font-weight: bold;">{{ $ticket->ticket_no }}</td>
                <td>{{ $ticket->created_at->format('Y-m-d') }}</td>
                <td>{{ $ticket->serviceType?->name ?? str_replace('_', ' ', $ticket->service_type) }}</td>
                <td style="text-transform: capitalize;">{{ $ticket->status }}</td>
            </tr>
            @endforeach
            @if($tickets->count() > 20)
            <tr>
                <td colspan="4" style="text-align: center; color: #999; font-style: italic;">... and {{ $tickets->count() - 20 }} more tickets not shown.</td>
            </tr>
            @endif
        </tbody>
    </table>

    <div class="footer">
        Generated by IT Helpdesk System on {{ now()->format('Y-m-d H:i:s') }}
    </div>

</body>
</html>
