<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>IT Helpdesk Report</title>
    <style>
        body { font-family: sans-serif; color: #2d2d2d; font-size: 12px; line-height: 1.5; margin: 0; padding: 20px; }
        h1 { font-size: 20px; border-bottom: 1px solid #2d2d2d; padding-bottom: 10px; margin-bottom: 20px; text-transform: uppercase; letter-spacing: 1px; }
        h2 { font-size: 14px; margin-top: 30px; margin-bottom: 10px; text-transform: uppercase; color: #555; }
        .grid { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .grid td { padding: 10px; border: 1px solid #e5e5e5; text-align: center; }
        .grid td.label { font-size: 10px; text-transform: uppercase; color: #555; letter-spacing: 1px; }
        .grid td.value { font-size: 24px; font-weight: bold; }
        .grid td.dark { background: #2d2d2d; color: #fff; }
        .grid td.dark .label { color: #aaa; }
        table.list { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        table.list th { background: #f7f7f7; color: #555; font-size: 10px; text-transform: uppercase; padding: 8px; text-align: left; border-bottom: 1px solid #e5e5e5; }
        table.list td { padding: 8px; border-bottom: 1px solid #f0f0f0; }
        .footer { position: fixed; bottom: -20px; left: 0; right: 0; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #e5e5e5; padding-top: 10px; }
    </style>
</head>
<body>

    <h1>{{ $title }}</h1>

    <h2>Tickets</h2>
    <table class="list">
        <thead>
            <tr>
                <th>Ticket No</th>
                <th>Date</th>
                <th>Service Type</th>
                <th>Requirement Description</th>
                <th>Status</th>
                <th>Accomplished By</th>
            </tr>
        </thead>
        <tbody>
            @forelse($resolvedTickets as $ticket)
            <tr>
                <td style="font-weight: bold;">{{ $ticket->ticket_no }}</td>
                <td>{{ $ticket->created_at->format('Y-m-d') }}</td>
                <td>{{ $ticket->serviceType?->name ?? str_replace('_', ' ', $ticket->service_type) }}</td>
                <td>{{ $ticket->description }}</td>
                <td>{{ \App\Models\TicketLog::formatStatusLabel($ticket->status) }}</td>
                <td>{{ $ticket->assignedTo?->name ?? 'N/A' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="5" style="text-align: center; color: #999; font-style: italic;">No tickets found for this period.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by IT Helpdesk on {{ now()->format('Y-m-d H:i:s') }}
    </div>

</body>
</html>
